# Enable composefs
# See: https://fedoraproject.org/wiki/Changes/ComposefsAtomicDesktops
postprocess:
  - |
    #!/usr/bin/bash
    set -xeuo pipefail

    install -dm 0755 -o 0 -g 0 /usr/lib/ostree
    cat >> /usr/lib/ostree/prepare-root.conf << 'EOF'
    [sysroot]
    readonly = true
    EOF

  - |
    #!/usr/bin/bash
    set -xeuo pipefail

    cat >> /usr/lib/ostree/prepare-root.conf << 'EOF'
    [composefs]
    enabled = yes
    EOF
