name: Build and push image

on:
  push:
    paths:
      - '*.yaml'
      - '.github/workflows/build.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

concurrency:
  group: image-build
  cancel-in-progress: true

jobs:
  nvidia-kmod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      kernelver: ${{ steps.kernelver.outputs.kernelver }}
      nvidiaver: ${{ steps.kernelver.outputs.nvidiaver }}
    container:
      image: ghcr.io/${{ github.repository }}/buildroot:latest
    steps:
      - name: Repo
        run: |
          cat << 'EOF' > /etc/yum.repos.d/nvidia-build.repo
          [nvidia-build]
          name=solopasha/nvidia-build
          baseurl=https://github.com/solopasha/nvidia-build/releases/download/
          type=rpm-md
          skip_if_unavailable=True
          gpgcheck=1
          gpgkey=https://raw.githubusercontent.com/solopasha/kde6-copr/refs/heads/unstable/RPM-GPG-KEY-solopasha
          repo_gpgcheck=0
          enabled=1
          enabled_metadata=1
          EOF

      - name: Get latest kernel and nvidia version
        id: kernelver
        run: |
          echo "kernelver=$(dnf -q --refresh rq kernel --latest-limit=1 --qf '%{VERSION}-%{RELEASE}.%{ARCH}')" >> $GITHUB_OUTPUT
          echo "nvidiaver=$(dnf -y -q --disablerepo=\* --enablerepo=nvidia-build \
                          rq akmod-nvidia --latest-limit=1 --qf '%{VERSION}-%{RELEASE}.%{ARCH}')" >> $GITHUB_OUTPUT

      - name: Check if kmod is up to date
        uses: actions/cache/restore@v4
        id: repocache
        with:
          lookup-only: true
          path: nvidia-kmod-repo
          key: nvidia-kmod-repo-${{ steps.kernelver.outputs.kernelver }}-${{ steps.kernelver.outputs.nvidiaver }}

      - name: Prepare
        if: steps.repocache.outputs.cache-hit != 'true'
        run: |
          dnf -y up && dnf -y install \
            gnupg2 \
            rpm-sign \
            createrepo_c \
            distribution-gpg-keys \
            git-core \
            kernel-${{ steps.kernelver.outputs.kernelver }} \
            kernel-devel-${{ steps.kernelver.outputs.kernelver }}

      - name: Checkout
        if: steps.repocache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Keys
        if: steps.repocache.outputs.cache-hit != 'true'
        env:
          KMOD_SIGN_KEY: ${{ secrets.KMOD_SIGN_KEY }}
          GPGKEY: ${{ secrets.GPGKEY }}
        run: |
          echo "$KMOD_SIGN_KEY" | install -Dm0644 /dev/stdin /etc/pki/akmods/private/private_key.priv
          install -Dm0644 public_key.der /etc/pki/akmods/certs/public_key.der
          echo "$GPGKEY" | gpg --import

      - name: Build kmod-nvidia
        if: steps.repocache.outputs.cache-hit != 'true'
        run: |
          echo "%_without_kmod_nvidia_detect 1" > /etc/rpm/macros.nvidia-kmod
          dnf -y in --setopt=install_weak_deps=0 akmod-nvidia-${{ steps.kernelver.outputs.nvidiaver }}
          akmods --force --kernel "${{ steps.kernelver.outputs.kernelver }}"
          modinfo /usr/lib/modules/"${{ steps.kernelver.outputs.kernelver }}"/extra/nvidia/nvidia{,-drm,-modeset,-peermem,-uvm}.ko > /dev/null || \
            (cat /var/cache/akmods/nvidia/*-for-*.log && exit 1)
          mkdir nvidia-kmod-repo
          cp /var/cache/akmods/nvidia/*.rpm nvidia-kmod-repo

      - name: Sign
        if: steps.repocache.outputs.cache-hit != 'true'
        run: |
          rpm -D "%_gpg_name ${{ github.repository_owner }}" --addsign ./nvidia-kmod-repo/*.rpm

      - name: Create repo
        if: steps.repocache.outputs.cache-hit != 'true'
        run: |
          pushd nvidia-kmod-repo
          createrepo_c .

      - name: Save repo
        if: steps.repocache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: nvidia-kmod-repo
          key: nvidia-kmod-repo-${{ steps.kernelver.outputs.kernelver }}-${{ steps.kernelver.outputs.nvidiaver }}

  main:
    needs: nvidia-kmod
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    container:
      image: ghcr.io/${{ github.repository }}/buildroot:latest
      options: --privileged
    env:
      IMAGENAME: ghcr.io/${{ github.repository }}/kde-unstable-atomic

    steps:
      - name: Prepare
        run: |
          cat << EOF > /etc/containers/registries.d/sigstore.yaml
          docker:
            $IMAGENAME:
              use-sigstore-attachments: true
          EOF
          cp /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-$(rpm -E %fedora) /etc/pki/rpm-gpg/
          cp /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$(rpm -E %fedora) /etc/pki/rpm-gpg/
          rpm --import https://raw.githubusercontent.com/solopasha/kde6-copr/refs/heads/unstable/RPM-GPG-KEY-solopasha

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download nvidia repo
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: nvidia-kmod-repo
          key: nvidia-kmod-repo-${{ needs.nvidia-kmod.outputs.kernelver }}-${{ needs.nvidia-kmod.outputs.nvidiaver }}

      - name: Specify repo path
        run: |
          sed -i "s|@@PATH@@|$(realpath nvidia-kmod-repo)|" nvidia.repo

      - name: Figure out version
        id: buildid
        run: |
          set -x
          date_now="$(date -u "+%Y%m%d")"
          fedora_version="$(rpm-ostree compose tree --print-only kinoite.yaml | jq -r '."mutate-os-release"')"
          version_remote="$(skopeo inspect "docker://${IMAGENAME}:${fedora_version}" | jq -r '.Labels."org.opencontainers.image.version"' || :)"
          if [[ -n "${version_remote}" ]]; then
            date_remote="${version_remote%\.*}"
            date_remote="${date_remote#*\.}"
          fi
          if [[ "${date_now}" == "${date_remote}" ]]; then
            patch="${version_remote##*\.}"
            ((patch++)) || true
            buildid="${date_now}.${patch}"
          else
            buildid="${date_now}.0"
          fi

          echo "fedora_version=${fedora_version}" >> $GITHUB_OUTPUT
          echo "buildid=${buildid}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          cp RPM-GPG-KEY-${{ github.repository_owner }} /etc/pki/rpm-gpg/
          mkdir -p cache

          echo "Composing kinoite ${{ steps.buildid.outputs.fedora_version }}.${{ steps.buildid.outputs.buildid }} ..."

          rpm-ostree compose image \
            --cachedir=cache \
            --initialize \
            --max-layers 96 \
            --format oci \
            --label="org.opencontainers.image.version=${{ steps.buildid.outputs.buildid }}" \
            "kinoite.yaml" \
            "kinoite-build"

      - name: Key
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_PASSPHRASE: ${{ secrets.SIGN_PASSPHRASE }}
        run: |
          echo "$SIGN_KEY" > ${{ github.repository_owner }}.private
          echo "$SIGN_PASSPHRASE" > ${{ github.repository_owner }}.passphrase

      - name: Push
        env:
          SKOPEO_ARGS: "--sign-by-sigstore-private-key ${{ github.repository_owner }}.private --sign-passphrase-file ${{ github.repository_owner }}.passphrase --retry-times 3 --dest-compress-format zstd"
        run: |
          skopeo login --username "${{ github.repository_owner }}" --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io

          for i in {1..5}; do
            skopeo copy ${SKOPEO_ARGS} \
              "oci:kinoite-build" \
              "docker://${IMAGENAME}:${{ steps.buildid.outputs.fedora_version }}.${{ steps.buildid.outputs.buildid }}" && break || sleep $((5 * i))
          done

          for i in {1..5}; do
            skopeo copy ${SKOPEO_ARGS} \
              "docker://${IMAGENAME}:${{ steps.buildid.outputs.fedora_version }}.${{ steps.buildid.outputs.buildid }}" \
              "docker://${IMAGENAME}:${{ steps.buildid.outputs.fedora_version }}" && break || sleep $((5 * i))
          done
